### ISSUE TITLE
Readme misses dependencies

### ISSUE THREAD

**Issue by LukasWerfel** [manuel-uberti/boodle#7]
Hi @manuel-uberti,
really cool project! I just wanted to point out that the [readme](https://github.com/manuel-uberti/boodle#usage) is missing to mention that Java and CLJ are also requirements for the usage! 

Best regards

**Comment by manuel-uberti** [comment]
Hi, thanks. You mean the Clojure CLI tools?

**Comment by LukasWerfel** [comment]
Yes! Both Java and CLJ tools deps have to be installed
